Case study on Supervised learning
Do the following in the iris dataset.
1. Read the dataset to the python environment.
2. Do necessary pre-processing steps.
3. Find out which classification model gives the best result to predict iris
species.(also do random forest algorithm


In [1]:
import numpy as np
import pandas as pd
from pandas import Series ,DataFrame
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats


In [2]:
data=pd.read_csv(r"C:\Users\hp\Desktop\Data Science Activites\classification assigment\iris csv.csv")
data

SL   SW   PL   PW  Classification
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    NaN  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  NaN  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
data.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  NaN  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [4]:
data.shape

(150, 5)

In [5]:
data.isna().sum()

SL                7
SW                6
PL                6
PW                0
Classification    0
dtype: int64

In [6]:
data.columns

Index(['SL', 'SW', 'PL', 'PW', 'Classification'], dtype='object')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              143 non-null    float64
 1   SW              144 non-null    float64
 2   PL              144 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [37]:
#label encoding
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
binary_features= ['Classification']   

for i in binary_features:
    label_encoders[i] = LabelEncoder()
    data[i] = label_encoders[i].fit_transform(data[i])  
  

In [38]:
data

SL   SW    PL   PW  Classification
0    5.1  3.5  1.40  0.2               0
1    4.9  3.0  1.40  0.2               0
2    5.0  3.2  1.30  0.2               0
3    4.6  3.1  1.50  0.2               0
4    5.0  3.6  1.40  0.2               0
..   ...  ...   ...  ...             ...
145  6.7  3.0  5.20  2.3               2
146  6.3  2.5  5.00  1.9               2
147  6.5  3.0  5.55  2.0               2
148  6.2  3.4  5.40  2.3               2
149  5.9  3.0  5.10  1.8               2

[147 rows x 5 columns]

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 147 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              147 non-null    float64
 1   SW              147 non-null    float64
 2   PL              147 non-null    float64
 3   PW              147 non-null    float64
 4   Classification  147 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.9 KB


In [40]:
#filling null values

In [41]:
x=data.drop(['Classification'],axis=1)
y=(data['Classification'])

In [42]:
data.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [43]:
data.groupby('Classification')[['SL']].median()

SL
Classification      
0               5.00
1               5.85
2               6.50

In [44]:
data.groupby('Classification')[['SW']].median()

SW
Classification     
0               3.4
1               2.8
2               3.0

In [45]:
data.groupby('Classification')[['PL']].median()

PL
Classification      
0               1.50
1               4.35
2               5.55

In [46]:
data['SL'] = data['SL'].fillna(data.groupby('Classification')['SL'].transform('median'))
data['SW'] = data['SW'].fillna(data.groupby('Classification')['SW'].transform('median'))
data['PL'] = data['PL'].fillna(data.groupby('Classification')['PL'].transform('median'))

In [47]:
data.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [48]:
data


SL   SW    PL   PW  Classification
0    5.1  3.5  1.40  0.2               0
1    4.9  3.0  1.40  0.2               0
2    5.0  3.2  1.30  0.2               0
3    4.6  3.1  1.50  0.2               0
4    5.0  3.6  1.40  0.2               0
..   ...  ...   ...  ...             ...
145  6.7  3.0  5.20  2.3               2
146  6.3  2.5  5.00  1.9               2
147  6.5  3.0  5.55  2.0               2
148  6.2  3.4  5.40  2.3               2
149  5.9  3.0  5.10  1.8               2

[147 rows x 5 columns]

In [49]:
#spliting of data
from  sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [50]:
# split outcome
data.shape

(147, 5)

In [51]:
x_train.shape

(117, 4)

# 1 logistic regression

In [130]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test) 
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train, y_train)

LogisticRegression()

In [131]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11  0  0]
 [ 0  9  1]
 [ 0  0  9]]


0.9666666666666667

# KNN

In [103]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [104]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11  0  0]
 [ 0  9  1]
 [ 0  0  9]]


0.9666666666666667

# Random Forest

In [105]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [106]:
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11  0  0]
 [ 0  9  1]
 [ 0  0  9]]


0.9666666666666667

# Kernal SVM

In [107]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x_train, y_train)

SVC(random_state=0)

In [108]:
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[11  0  0]
 [ 0 10  0]
 [ 0  0  9]]


1.0

# DecisionTreeClassifier

In [109]:
from sklearn.tree import DecisionTreeClassifier


In [110]:

dt_model=DecisionTreeClassifier()
dt_model.fit(x_train,y_train)
y_predict=dt_model.predict(x_test)


In [111]:
accuracy_score(y_test,y_predict)

0.9666666666666667

In [112]:
confusion_matrix(y_test,y_predict)

array([[11,  0,  0],
       [ 0,  9,  1],
       [ 0,  0,  9]], dtype=int64)

# GRADIENTBOOSTINGCLASSIFIER

In [113]:
from sklearn.ensemble import GradientBoostingClassifier

In [114]:

GBC=GradientBoostingClassifier()
GBC.fit(x_train,y_train)
y_predict=GBC.predict(x_test)


In [115]:
accuracy_score(y_test,y_predict)

0.9666666666666667

In [116]:
confusion_matrix(y_test,y_predict)

array([[11,  0,  0],
       [ 0,  9,  1],
       [ 0,  0,  9]], dtype=int64)

In [ ]:
#all thhe classification models performs good